creation_rules:
  - path_regex: ^secrets/.*\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age: ["age1REPLACEPUBLICKEYONPREM..."]
  - path_regex: ^clusters/.*/secrets/.*\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age: ["age1REPLACEPUBLICKEY-ANOTHERCLUSTER..."]
