apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-root
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/tekenstam/k8s-homelab
    targetRevision: main
    path: apps
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
