apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shared-infra
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-infra"
    spec:
      project: default
      destination:
        server: "{{server}}"
        namespace: argocd
      source:
        repoURL: https://github.com/tekenstam/k8s-homelab
        targetRevision: main
        path: apps/infra
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ CreateNamespace=true ]
