apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
stringData:
  creds: |
    [default]
    aws_access_key_id = <REPLACE_ME>
    aws_secret_access_key = <REPLACE_ME>
    region = us-east-1
