apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-cred
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<REPLACE_ME>"
  AWS_SECRET_ACCESS_KEY: "<REPLACE_ME>"
  AWS_ENDPOINTS: "http://nas-01.ekenstam.dev:9000"
